sudo: false

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script: "bin/rspec"

language: ruby

cache: bundler

rvm:
  - 2.1.0

services:
  - postgresql

addons:
  postgresql: "9.4"  